services:
  - type: web
    name: airbnb-backend
    env: docker
    repo: https://github.com/LIBERTY-D/airbnb-backend.git
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      # Spring Profile
      - key: ACTIVE_PROFILE
        value: prod

      # Database
      - key: POSTGRES_SERVICE
        value: airbnb-db
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: ""
      - key: POSTGRES_USER
        value: ""
      - key: POSTGRES_PASS
        value: ""

      # Server Port
      - key: APP_PORT
        value: "8080"

      # JPA / Hibernate
      - key: DDL_AUTO
        value: update

      # Mail Settings
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: ""
      - key: MAIL_PASSWORD
        value: ""
      - key: MAIL_ENABLE
        value: "true"

      # OAuth: GitHub
      - key: GITHUB_CLIENT_ID
        value: ""
      - key: GITHUB_CLIENT_SECRET
        value: ""

      # OAuth: Google
      - key: GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""

      # JWT
      - key: JWT_EXP_ACCESS_TOKEN
        value: "3600000"
      - key: JWT_EXP_REFRESH_TOKEN
        value: "8600000"
      - key: JWT_SECRET
        value: ""

      # URLs
      - key: REDIRECT_URL
        value: https://yourfrontend.com/logged-in
      - key: REDIRECT_VERIFY
        value: https://yourfrontend.com/verify
      - key: ACCOUNT_CREATED_URL
        value: https://yourbackend.com/api/v1/users/verify?token=

      # Pexel API
      - key: PEXEL_KEY
        value: ""

      # CORS
      - key: ORIGINS
        value: ""

      # Admin
      - key: APP_EMAIL
        value: ""
      - key: APP_PASSWORD
        value: ""
      - key: APP_USERNAME
        value: supertheuser

databases:
  - name: airbnb-db
    databaseName: airbnb
    user: airbnb_user
    password: ""
