services:
  - type: web
    name: airbnb-backend
    env: docker
    repo: https://github.com/LIBERTY-D/airbnb-backend.git
    dockerfilePath: ./Dockerfile                    # path to your Dockerfile
    plan: free                                      # or choose another plan
    envVars:
      - key: ACTIVE_PROFILE
        value: prod
      - key: GITHUB_CLIENT_ID
        fromSecret: GITHUB_CLIENT_ID_SECRET
      - key: GITHUB_CLIENT_SECRET
        fromSecret: GITHUB_CLIENT_SECRET_SECRET
      - key: GOOGLE_CLIENT_ID
        fromSecret: GOOGLE_CLIENT_ID_SECRET
      - key: GOOGLE_CLIENT_SECRET
        fromSecret: GOOGLE_CLIENT_SECRET_SECRET
      - key: POSTGRES_SERVICE
        value: your-postgres-host
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: airbnb
      - key: POSTGRES_USER
        value: airbnb_user
      - key: POSTGRES_PASS
        fromSecret: POSTGRES_PASS_SECRET
      - key: DDL_AUTO
        value: update
      - key: MAIL_HOST
        value: smtp.mailprovider.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        fromSecret: MAIL_USERNAME_SECRET
      - key: MAIL_PASSWORD
        fromSecret: MAIL_PASSWORD_SECRET
      - key: APP_PORT
        value: "8080"
      - key: REDIRECT_URL
        value: https://yourapp.com/redirect
      - key: REDIRECT_VERIFY
        value: some-verify-token
      - key: ACCOUNT_CREATED_URL
        value: https://yourapp.com/account-created
      - key: PEXEL_KEY
        fromSecret: PEXEL_KEY_SECRET
      - key: JWT_EXP_ACCESS_TOKEN
        value: "3600"
      - key: JWT_EXP_REFRESH_TOKEN
        value: "86400"
      - key: JWT_SECRET
        fromSecret: JWT_SECRET_SECRET
      - key: ORIGINS
        value: https://yourfrontend.com
      - key: APP_EMAIL
        fromSecret: APP_EMAIL_SECRET
      - key: APP_PASSWORD
        fromSecret: APP_PASSWORD_SECRET
      - key: APP_USERNAME
        value: admin
      - key: MAIL_ENABLE
        value: "true"

databases:
  - name: airbnb-db
    databaseName: airbnb
    user: airbnb_user
    password: # Set this as a secret in the Render dashboard
