#PROFILE
ACTIVE_PROFILE: ${ACTIVE_PROFILE}

#GOOGLE
GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

#GITHUB

GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

#APP
APP_PORT: ${APP_PORT}


#DB
POSTGRES_SERVICE: ${POSTGRES_SERVICE}
POSTGRES_PORT: ${POSTGRES_PORT}
POSTGRES_DB: ${POSTGRES_DB}
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_PASS: ${POSTGRES_PASS}

# JPA
DDL_AUTO: ${DDL_AUTO}


#REDIRECT
REDIRECT_URL: ${REDIRECT_URL}
REDIRECT_VERIFY: ${REDIRECT_VERIFY}
ACCOUNT_CREATED_URL: http://localhost:9090/api/v1/users/verify?token=

#JWT
JWT_EXP_ACCESS_TOKEN: ${JWT_EXP_ACCESS_TOKEN}
JWT_EXP_REFRESH_TOKEN: ${JWT_EXP_REFRESH_TOKEN}
JWT_SECRET: ${JWT_SECRET}


#ORIGINS FOR CORS
ORIGINS: ${ORIGINS}


# ADMIN OF APP
APP_EMAIL: ${APP_EMAIL}
APP_PASSWORD: ${APP_PASSWORD}
APP_USERNAME: ${APP_USERNAME}

#EMAIL
MAIL_PORT: ${MAIL_PORT}
MAIL_HOST: ${MAIL_HOST}
MAIL_USERNAME: ${MAIL_USERNAME}
MAIL_PASSWORD: ${MAIL_PASSWORD}
MAIL_ENABLE: true


#PEXELS
PEXEL_KEY: ${PEXEL_KEY}